DATABASE_URL: ENC[AES256_GCM,data:aJ069eoj/uyUlysEGWLuGdnM1skMSdNxaRYty38UMvEPkXSsvqENzym95XBgqUizrwm87iglZ9S3,iv:q2aOSIseFNvH8WEKKOpkPwqbXQ1apfKwU7TYAYzpMdc=,tag:p/1rgaPqnQbC8U+9DYUFBA==,type:str]
NODE_ENV: ENC[AES256_GCM,data:jTW7GORHYkS/xaw=,iv:txcVBj+ctdtXyU/j0xq5pAU31O+3EQ0JUAu1ReUunkU=,tag:O0TnooW6K7nqWObvywoD4g==,type:str]
NEXT_PUBLIC_MAIN_APP_URL: ENC[AES256_GCM,data:4l73CIEw9cAazglGfybxsPIvxx4M,iv:SV9Uo++pJVQnumH5Jj5TKzEMtZPUWEud+RygFSiBE6A=,tag:UWaopzuXhoe1CSHtaZoQ1Q==,type:str]
NEXT_PUBLIC_LANDING_URL: ENC[AES256_GCM,data:HYkLtRW2DnBcYjx+4xAixL5LFJIe,iv:Z79euNgW6hqM9QJ7nvr2sRz3XLZSOBnc+T3rTZiLaTs=,tag:orUaRDqIENUH0Z5YgGxD5Q==,type:str]
SESSION_SECRET: ENC[AES256_GCM,data:3cDiB7Fffrw4bGjydILHushZAM7/i+oSVG+Vx3vSluwozvnKoe+pYnDzxoU/I2wlKvle,iv:bEVG/wck1jEH58tIQ7I1zd/apYa2aXQ5O4dC0xrzVxo=,tag:CvB8NHFYS8gd9uZOxeceEA==,type:str]
RESEND_API_KEY: ENC[AES256_GCM,data:gDhKxfj9dtXA73v+NS5O+HGzTYF9DRR7pSsrQgipEzT5qrQn,iv:YdKvT3S4EUCxCDehVXn66b+rtS4zpRxa6wRS2JAbcAc=,tag:z9iRUWeVeen6xxSq1HpT+w==,type:str]
RESEND_FROM_EMAIL: ENC[AES256_GCM,data:XeByODN4J6ZptOBKdkLOkqPMBOqlz6hR,iv:yFLGTTYABk/c9ErmKEHgZH/nT+XZzracmF4I4RrXoG8=,tag:hLcstnGbnxsI9bJd3p8FiQ==,type:str]
sops:
    age:
        - recipient: age1t8uvd9nppt3fcdgtzajlwmcwh0dntdk7axvshkvq5hsjrkv2rc6shhlgg9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkdTJYUHZJMm02N0pnVHZ3
            UUorSkNPcjlncDlvUnpadjRkT1YvNGRmVUdjCkNBelFzb2MzRGkxOCtqb3pHN1J5
            YkZyY21wNGc4ZXB3WTF5dU8rSGtnSlkKLS0tIGxKVXc2QzQrWW5SbmZtOHJVMzBJ
            am42VHVHSGFTZlNtaFYrQ3V3QlhUK2sKqAPjEQ2AORL4G7O3fagKzyFhi8bMYQ4c
            2oNQpg5a+/Cxvkgg4FDjaDDUkzGxkI/P+y9nqxMoXDXxnBTb02BWmg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-04T06:56:30Z"
    mac: ENC[AES256_GCM,data:bhChf0uTyVnumSLzNNxcK8DDex0ddP+1Mdni/iZmXZmmV0j0eA0EOXGMQjX08wJ3V7F6qhfEJ2R2QzF+uHMmIkua4f8ouPxc5mS77DKHnlLvxqG9aPJfCsq/j0KxKOIEjzAzQgN6pqrfn2zKHJIs28SrzUPxOfYGKoIM8Xp44qE=,iv:q+LobXr+PmhpuCzA5Jajcshz+24q3yA5yWoBWu6OYEk=,tag:NV+XIP+JDR1lLF4oUlDKSw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
